run:
  concurrency: 4
  timeout: 30m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    # - src/external_libs
  skip-dirs-use-default: false
  modules-download-mode: readonly
  allow-parallel-runners: false
  go: ""

linters:
  fast: false
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errcheck 
    - errname
    - errorlint
    - exportloopref
    - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - hugeParam
      - rangeExprCopy
      - rangeValCopy

  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  govet:
    disable:
      - fieldalignment

  nakedret:
    # No naked returns, ever.
    max-func-lines: 1 # Default: 30

  tagliatelle:
    case:
      rules:
        json: snake 
        yaml: snake
        xml: camel
        bson: camel
        avro: snake
        mapstructure: kebab

output:
  print-issued-lines: false
  print-linter-name: true
  uniq-by-line: false
  path-prefix: ""
  sort-results: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false