// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"fmt"
	"github.com/sevigo/shugosha/pkg/api"
	"github.com/sevigo/shugosha/pkg/backupmanager"
	"github.com/sevigo/shugosha/pkg/config"
	"github.com/sevigo/shugosha/pkg/db"
	"github.com/sevigo/shugosha/pkg/fsmonitor"
	"github.com/sevigo/shugosha/pkg/model"
	"github.com/sevigo/shugosha/pkg/provider"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	db, err := dbProvider()
	if err != nil {
		return nil, err
	}
	configManager, err := configManagerProvider(db)
	if err != nil {
		return nil, err
	}
	monitor, err := fsMonitorProvider()
	if err != nil {
		return nil, err
	}
	backupConfig, err := backupConfigProvider(configManager)
	if err != nil {
		return nil, err
	}
	v := backupProviders(backupConfig, monitor)
	backupManager, err := backupManagerProvider(db, monitor, v)
	if err != nil {
		return nil, err
	}
	providerMetaInfoGetter := providerMetaInfoGetterProvider(backupManager)
	server := apiServiceProvider(configManager, providerMetaInfoGetter)
	app := NewApp(configManager, backupManager, monitor, server)
	return app, nil
}

// wire.go:

// App contains all dependencies of the application.
type App struct {
	ConfigManager model.ConfigManager
	BackupManager *backupmanager.BackupManager
	Monitor       *fsmonitor.Monitor
	Server        *api.Server
}

// NewApp creates a new instance of your application
func NewApp(configManager model.ConfigManager, backupManager *backupmanager.BackupManager, monitor *fsmonitor.Monitor, server *api.Server) *App {
	return &App{
		ConfigManager: configManager,
		BackupManager: backupManager,
		Monitor:       monitor,
		Server:        server,
	}
}

func fsMonitorProvider() (*fsmonitor.Monitor, error) {
	monitor, err := fsmonitor.New(fsmonitor.DefaultConfig())
	if err != nil {
		return nil, fmt.Errorf("Failed to setup file system monitor: %w", err)
	}
	return monitor, nil
}

func backupManagerProvider(storage model.DB, monitor *fsmonitor.Monitor, providers map[string]model.Provider) (*backupmanager.BackupManager, error) {
	backupManager, err := backupmanager.NewBackupManager(storage, monitor, providers)
	if err != nil {
		return nil, fmt.Errorf("failed to create backup manager: %w", err)
	}
	return backupManager, nil
}

func dbProvider() (model.DB, error) {
	storage, err := db.NewBadgerDB(".db/")
	if err != nil {
		return nil, fmt.Errorf("failed to initialize database: %w", err)
	}
	return storage, nil
}

func apiServiceProvider(cm model.ConfigManager, g model.ProviderMetaInfoGetter) *api.Server {
	return api.NewServer(cm, g)
}

func configManagerProvider(storage model.DB) (model.ConfigManager, error) {
	configManager, err := config.NewConfigManager(storage)
	if err != nil {
		return nil, fmt.Errorf("Config manager initialization failed: %w", err)
	}

	return configManager, nil
}

func backupProviders(backupConfig *model.BackupConfig, monitor *fsmonitor.Monitor) map[string]model.Provider {
	return provider.InitializeProviders(backupConfig, monitor)
}

func backupConfigProvider(configManager model.ConfigManager) (*model.BackupConfig, error) {
	return configManager.LoadConfig()
}

func providerMetaInfoGetterProvider(bm *backupmanager.BackupManager) model.ProviderMetaInfoGetter {
	return bm
}
